// Fleet service registry — the routing target set for the dispatch meta-API.
// Each entry: stable id, live base URL, paid endpoint, price, network, intent
// signature (the classifier routes on it), and param hints. Endpoints + prices
// verified live against each service's /.well-known/x402.json + source 2026-06-29.
// Updated 2026-09-21: added zFinia (WCAG contrast + field-compat) and external
// crypto data API (7 endpoints).

const NETWORK_MAINNET = "eip155:8453";

const SERVICES = [
  {
    id: "suprapack",
    name: "SupraPack — skill discovery",
    base: "https://suprapack-x402.fly.dev",
    endpoint: "/api/find-skill",
    method: "POST",
    price: "$0.03",
    network: NETWORK_MAINNET,
    intent: "Find or search Claude Code skills/agents by keyword or goal. Discover a capability to load on demand.",
    params_hint: { goal: "string (what skill/capability to find)" },
  },
  {
    id: "power-pack",
    name: "Power Pack — outreach email scorer",
    base: "https://power-pack-x402.fly.dev",
    endpoint: "/api/score-email",
    method: "POST",
    price: "$0.01",
    network: NETWORK_MAINNET,
    intent: "Score or critique a cold/outreach/sales email for quality, deliverability, and persuasion.",
    params_hint: { subject: "string (email subject)", body: "string (email body)" },
  },
  {
    id: "royal-ruby",
    name: "Royal Ruby — US consumer-law citation lookup",
    base: "https://royal-ruby-x402.fly.dev",
    endpoint: "/api/law-lookup",
    method: "POST",
    price: "$0.01",
    network: NETWORK_MAINNET,
    intent: "Look up US consumer-protection law citations (FDCPA, FCRA, TILA, etc.) for a topic or situation. Informational, not legal advice.",
    params_hint: { topic: "string (consumer-law topic or question)" },
  },
  {
    id: "sentry-forge",
    name: "Sentry Forge — debt dispute pack",
    base: "https://sentry-forge-x402.fly.dev",
    endpoint: "/api/dispute-pack",
    method: "POST",
    price: "$0.50",
    network: NETWORK_MAINNET,
    intent: "Generate a consumer-debt dispute letter / dispute pack for a collection or credit-report item.",
    params_hint: { debt: "string (the debt/collection situation)" },
  },
  {
    id: "vault-pro",
    name: "Vault Pro — Obsidian project scaffolder",
    base: "https://vault-pro-x402.fly.dev",
    endpoint: "/api/scaffold-project",
    method: "POST",
    price: "$0.05",
    network: NETWORK_MAINNET,
    intent: "Scaffold an Obsidian project or agent vault structure from a goal/description.",
    params_hint: { goal: "string (what to scaffold)" },
  },
  {
    id: "tradingagents",
    name: "TradingAgents — multi-agent ticker analysis",
    base: "https://tradingagents-x402.fly.dev",
    endpoint: "/api/analyze-ticker",
    method: "POST",
    price: "$0.05",
    network: NETWORK_MAINNET,
    intent: "Run a multi-agent LLM analysis/consensus on a stock ticker for a buy/hold/sell view.",
    params_hint: { ticker: "string (stock symbol)" },
  },
  {
    id: "nanobanana",
    name: "Nanobanana — paid image generation",
    base: "https://nanobanana-x402.fly.dev",
    endpoint: "/api/generate-image",
    method: "POST",
    price: "$0.01",
    network: NETWORK_MAINNET,
    intent: "Generate an image from a text prompt. (Use /api/edit-image to edit an existing image.)",
    params_hint: { prompt: "string (image prompt)" },
  },
  {
    id: "nft-alpha",
    name: "NFT Alpha — OpenSea market signals",
    base: "https://nft-alpha-x402.fly.dev",
    endpoint: "/api/nft-signal",
    method: "POST",
    price: "$0.10",
    network: NETWORK_MAINNET,
    intent: "Get real-time OpenSea market signals for a watched NFT collection — floor pressure, listings, sales, bids, sell-through.",
    params_hint: { collection: "string (collection slug or address)" },
  },
  {
    id: "dispute-forge",
    name: "Dispute Forge — FCRA dispute letter + on-chain certificate",
    base: "https://dispute-forge-x402.fly.dev",
    endpoint: "/api/dispute-pack",
    method: "POST",
    price: "$0.75",
    network: NETWORK_MAINNET,
    intent: "Generate an FCRA-compliant consumer credit dispute letter and a unique on-chain SVG certificate of dispute for a creditor or credit bureau item.",
    params_hint: { creditor: "string (creditor name or account)", reason: "string (reason for dispute)" },
  },
  {
    id: "royal-feel",
    name: "Royal Feel — FTC compliance copy linter",
    base: "https://royal-feel-x402.fly.dev",
    endpoint: "/api/lint-copy",
    method: "POST",
    price: "$2.00",
    network: NETWORK_MAINNET,
    intent: "Lint or check marketing copy for FTC compliance, disease claims, or weight-loss hype.",
    params_hint: { text: "string (marketing copy)" },
  },
  {
    id: "contract-eye",
    name: "Contract Eye — AI contract clause analyzer",
    base: "https://contract-eye-x402.fly.dev",
    endpoint: "/api/analyze-contract",
    method: "POST",
    price: "$5.00",
    network: NETWORK_MAINNET,
    intent: "Analyze a contract for risky, one-sided, or unusual clauses.",
    params_hint: { text: "string (contract text)" },
  },
  {
    id: "lingua",
    name: "Lingua — AI translation and localization",
    base: "https://lingua-x402.fly.dev",
    endpoint: "/api/translate",
    method: "POST",
    price: "$1.00",
    network: NETWORK_MAINNET,
    intent: "Translate or localize text between language pairs, with cultural adaptation.",
    params_hint: { text: "string", to: "string", from: "string?" },
  },
  {
    id: "briefsnap",
    name: "BriefSnap — AI document summarizer",
    base: "https://briefsnap-x402.fly.dev",
    endpoint: "/api/summarize",
    method: "POST",
    price: "$1.00",
    network: NETWORK_MAINNET,
    intent: "Summarize articles, contracts, reports, or meeting notes into key points.",
    params_hint: { text: "string", length: "string?" },
  },
  {
    id: "escrow",
    name: "Escrow — agent-to-agent secure payment escrow",
    base: "https://escrow-x402.fly.dev",
    endpoint: "/api/escrow/create",
    method: "POST",
    price: "$0.05",
    network: NETWORK_MAINNET,
    intent: "Create a secure smart-contract escrow for agent-to-agent transactions.",
    params_hint: { buyer: "string", seller: "string", amount: "string" },
  },
  // zFinia — added 2026-09-21 (issue #5)
  {
    id: "zfinia-contrast",
    name: "zFinia — WCAG contrast calculator",
    base: "https://api.zfinia.com",
    endpoint: "/x402/v1/accessibility-contrast-calculator",
    method: "POST",
    price: "$0.001",
    network: NETWORK_MAINNET,
    intent: "Calculate WCAG 2.x sRGB contrast ratio / AA / AAA for any foreground/background color pair.",
    params_hint: { fg: "string (#RRGGBB)", bg: "string (#RRGGBB)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
  {
    id: "zfinia-compat",
    name: "zFinia — Field contract compatibility checker",
    base: "https://api.zfinia.com",
    endpoint: "/x402/v1/data-compatibility-checker",
    method: "POST",
    price: "$0.003",
    network: NETWORK_MAINNET,
    intent: "Check whether a data field contract (type, format, constraints) is compatible with a target schema.",
    params_hint: { field: "string (field name)", target_schema: "string (JSON Schema URL or inline)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
  // External Crypto Data API — added 2026-09-21 (issue #1)
  {
    id: "crypto-data-price",
    name: "Crypto Data Feed — real-time prices",
    base: "https://x402.167-172-95-184.nip.io",
    endpoint: "/price",
    method: "GET",
    price: "$0.01",
    network: NETWORK_MAINNET,
    intent: "Get BTC and ETH real-time prices in USDC on Base.",
    params_hint: { coin: "string (optional, defaults to both)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
  {
    id: "crypto-data-coin-price",
    name: "Crypto Data Feed — single coin price",
    base: "https://x402.167-172-95-184.nip.io",
    endpoint: "/price/{coin}",
    method: "GET",
    price: "$0.02",
    network: NETWORK_MAINNET,
    intent: "Get real-time price for any cryptocurrency in USDC on Base.",
    params_hint: { coin: "string (ticker symbol, e.g. SOL, AVAX)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
  {
    id: "crypto-data-portfolio",
    name: "Crypto Data Feed — portfolio valuation",
    base: "https://x402.167-172-95-184.nip.io",
    endpoint: "/portfolio",
    method: "GET",
    price: "$0.05",
    network: NETWORK_MAINNET,
    intent: "Get total portfolio valuation with per-asset breakdown across tracked wallets.",
    params_hint: { wallets: "string (comma-separated addresses)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
  {
    id: "crypto-data-opportunities",
    name: "Crypto Data Feed — latest opportunities",
    base: "https://x402.167-172-95-184.nip.io",
    endpoint: "/opportunities/latest",
    method: "GET",
    price: "$0.03",
    network: NETWORK_MAINNET,
    intent: "Get the latest on-chain arbitrage and yield opportunities across Base DeFi protocols.",
    params_hint: { protocol: "string (optional, filter by protocol)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
  {
    id: "crypto-data-morning",
    name: "Crypto Data Feed — morning briefing",
    base: "https://x402.167-172-95-184.nip.io",
    endpoint: "/briefing/morning",
    method: "GET",
    price: "$0.01",
    network: NETWORK_MAINNET,
    intent: "Get a daily morning briefing with market summary, key levels, and notable on-chain events.",
    params_hint: { date: "string (optional, ISO date)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
  {
    id: "crypto-data-research",
    name: "Crypto Data Feed — research reports",
    base: "https://x402.167-172-95-184.nip.io",
    endpoint: "/research/{topic}",
    method: "GET",
    price: "$0.02",
    network: NETWORK_MAINNET,
    intent: "Get a research report on a specific crypto topic, protocol, or market narrative.",
    params_hint: { topic: "string (research topic keyword)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
  {
    id: "crypto-data-mcp",
    name: "Crypto Data Feed — MCP tool call",
    base: "https://x402.167-172-95-184.nip.io",
    endpoint: "/mcp/call",
    method: "POST",
    price: "$0.05",
    network: NETWORK_MAINNET,
    intent: "Invoke any MCP tool exposed by the crypto data feed — natural language queries for prices, portfolio, opportunities, research.",
    params_hint: { tool: "string (tool name)", params: "object (tool-specific parameters)" },
    facilitator: "https://x402-agent-pay.com/facilitator",
  },
];

module.exports = { SERVICES, NETWORK_MAINNET };
